data_form:
    fields:
        media_file_selector_field: EveryWorkflow\MediaManagerBundle\Field\MediaFileSelectorField
        media_image_selector_field: EveryWorkflow\MediaManagerBundle\Field\MediaImageSelectorField
        media_image_gallery_selector_field: EveryWorkflow\MediaManagerBundle\Field\MediaImageGallerySelectorField
